apps/generator/views.py
import os
from queue import Queue

import cv2
from flask import (Blueprint, Response, current_app, flash, redirect,
                   render_template, request, send_from_directory, url_for)
from werkzeug.utils import secure_filename

from .camera import Camera
from .config import Config
from .predict_video import Highlight_Generator
from .select_person import get_person_coordinates

gen = Blueprint("generator", __name__, template_folder="templates", static_folder="static", static_url_path="/static/generator")

# ファイルの拡張子が有効かどうか
def is_allowed_file(file_name, allowed_extentions):
    return "." in file_name and file_name.rsplit(".", 1)[1].lower() in allowed_extentions

@gen.route("/", methods=["GET", "POST"])
def upload_file():
    if request.method == "POST":
        if "video" not in request.files:
            flash("ファイルがありません")
            return redirect(request.url)

        video = request.files["video"]
        if video.filename == "":
            flash("ビデオがありません")
            return redirect(request.url)

        if video and is_allowed_file(video.filename, Config.allowed_extentions):
            video_name = secure_filename(video.filename)
            video_path = os.path.join(current_app.config["UPLOAD_FOLDER"], video_name)
            video.save(video_path)
            return url_for('generator.image_file', filename=video_name)
    return render_template("generator/upload.html")

@gen.route("/select_scene", methods=["POST"])
def select_scene():
    if request.method == "POST":
        # 動画を取得する
        video_name = request.form['video_name']
        video_path = os.path.join(current_app.config["UPLOAD_FOLDER"], video_name)

        # 選択された場面の動画の秒数
        selected_time = request.form.get('video_currentTime', type=float)

        # 選択された場面を動画から切り抜く
        camera = Camera(video_path)
        frame = camera.get_frame_from_time(selected_time)
        scene_image_name = "selected_scene.jpg"
        scene_image_path = os.path.join(current_app.config["UPLOAD_FOLDER"], scene_image_name)
        cv2.imwrite(scene_image_path, frame)
        return url_for('generator.select_person', video_name=video_name, scene_image_name=scene_image_name)

@gen.route("/select_person/<video_name>/<scene_image_name>", methods=["GET", "POST"])
def select_person(video_name, scene_image_name):
    if request.method == "GET":
        # 場面を取得する
        image_path = os.path.join(current_app.config["UPLOAD_FOLDER"], scene_image_name)
        img = cv2.imread(image_path)
        height, width, _ = img.shape

        # 場面から人の座標を取得する
        coordinates = get_person_coordinates(img)
        person_image_list = []
        for id, coordinate in enumerate(coordinates, 1):
            # (pos1:左上, pos2:右下)の座標
            pos1, pos2 = coordinate
            left, top = pos1
            right, bottom = pos2
            # 場面から人を切り抜く
            person_image = img[top:bottom, left:right]
            person_image_name = f"person_{id}.jpg"
            person_image_path = os.path.join(current_app.config["UPLOAD_FOLDER"], person_image_name)
            cv2.imwrite(person_image_path, person_image)
            person_image_list.append((id, person_image_name, (top/height*100, (height-bottom)/height*100, left/width*100, (width-right)/width*100)))
        return render_template("generator/select_person.html", scene_image=scene_image_name, person_image_list=person_image_list)
    elif request.method == "POST":
        # ハイライトしたい人を取得する
        person_id = request.form['person_id']
        person_image_name = f"person_{person_id}.jpg"
        return render_template("generator/progress.html", video_name=video_name, target_person_image_name=person_image_name)

queue = Queue()

def event_stream(queue):
    while True:
        present = queue.get(True)
        sse_event = 'progress-item'
        if present >= 100:
            sse_event = 'last-item'
            present = 100
        yield f"event:{sse_event}\ndata:{present}\n\n"

@gen.route('/stream')
def stream():
    return Response(event_stream(queue), mimetype='text/event-stream')

@gen.route("/uploads/<video_name>/<target_person_image_name>")
def gen_highlight(video_name, target_person_image_name):
    highlight_gen = Highlight_Generator(video_name, target_person_image_name, os.path.join(current_app.config["UPLOAD_FOLDER"]))
    # 動画内でハイライトするフレームを生成する
    gen = highlight_gen.get_bestshot_frames(top=10)
    for percentage in gen:
        queue.put(percentage)

    gen = highlight_gen.create_highlight_video()
    for percentage in gen:
        queue.put(percentage)
    return render_template("generator/show_highlight_video.html", videolist=highlight_gen.videolist)

@gen.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)

apps/generator/templates/generator/base.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>スーピー</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
    {% block head %} {% endblock %}
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('generator.upload_file') }}">スーピー</a>
            </div>
        </nav>
    </header>

    <section class="container mt-5">
        {% block content %}{% endblock %}
    </section>
</body>

</html>

apps/generator/templates/generator/progress.html
{% extends "generator/base.html" %}

{% block content %}
<div class="progress_wrap bg-dark m-5" id="progress-bar-area">
    <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0"
        aria-valuemax="100" style="width:0%">
        <span class="progress-bar-label mx-2">0%</span>
    </div>
</div>
<div id="highlight-show"></div>

<script>
    $(() => {
        const source = new EventSource("/stream");
        source.addEventListener('progress-item', function (event) {
            $('.progress-bar').css('width', event.data + '%').attr('aria-valuenow', event.data);
            $('.progress-bar-label').text(event.data + '%');
        });
        source.addEventListener('last-item', (event) => {
            source.close();
            $('.progress-bar').css('width', '100%').attr('aria-valuenow', 100);
            $('.progress-bar-label').text('100%');
        });
        $.get('/uploads/{{ video_name }}/{{ target_person_image_name }}',
            (data) => {
                $('#progress-bar-area').delay(600).fadeOut(800).queue(() => {
                    $('#highlight-show').html(data).hide().fadeIn(800);
                });
            });
    });
</script>
{% endblock %}

apps/generator/templates/generator/select_person.html
{% extends "generator/base.html" %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('generator.static', filename='css/select_person.css') }}" />
{% endblock %}

{% block content %}
<h4>対象とする人物をクリックしてください</h4>
<div class="container scene-image-area">
    {% for (id, person_image, (top, bottom, left, right)) in person_image_list %}
    <form method="post" class="person-image-area"
        style="top:{{top}}%; bottom:{{bottom}}%; left:{{left}}%; right:{{right}}%;">
        <button type="submit" name="person_id" value="{{id}}">
            <img src="{{ url_for('generator.image_file', filename=person_image) }}">
        </button>
    </form>
    {% endfor %}
    <img src="{{ url_for('generator.image_file', filename=scene_image) }}">
</div>

<hr />
<a href="{{ url_for('generator.upload_file') }}">
    <button class="btn btn-primary btn-sm">戻る</button>
</a>
{% endblock %}

apps/generator/templates/generator/show_highlight_video.html
{% block head %}
<link rel="stylesheet" href="{{ url_for('generator.static', filename='css/show_highlight_video.css') }}" />
{% endblock %}

</head>
<div class="card col-md-7 dt-image-content">
    {% for video_name in videolist %}
    <header class="d-flex justify-content-between">
        <div></div>
        <a class="bi bi-box-arrow-in-down" href="{{ url_for('generator.image_file', filename=video_name) }}"
            download="{{ url_for('generator.image_file', filename=image_name) }}"></a>
    </header>
    <section>
        <video src="{{ url_for('generator.image_file', filename=video_name) }}" autoplay muted loop></video>
    </section>
    {% endfor %}
</div>

<div class="col-md-10 text-left dt-image-register-btn">
    <a href="{{ url_for('generator.upload_file') }}" class="btn btn-primary">topへ</a>
</div>

apps/generator/templates/generator/upload.html
{% extends "generator/base.html" %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('generator.static', filename='css/upload.css') }}" />
{% endblock %}

{% block content %}
<h4>アップロード画面</h4>
<p>ビデオを選択してください</p>
<form action="/" enctype=multipart/form-data>
    <input type=file name=file />
    <hr>
    <button id="upload-btn" type="button" class="btn btn-primary btn-sm">upload</button>
</form>

<div id="select_scene" style="display:none" disabled>
    <p>シークバーを動かしてハイライトしたい人物が写っている場面を選択してください</p>
    <div id="video-area"></div>
    <button id="select-btn" class="btn btn-primary btn-sm">選択する</button>
</div>

<div id="loader-bg">
    <div id="loader">
        <img src="{{ url_for('generator.static', filename='images/loading_image.gif') }}" width="80" height="80"
            alt="Now Loading..." />
        <p>Now Loading..</p>
    </div>
</div>

<script>
    $(() => {
        $('#upload-btn').click(() => {
            const $form = $('form');
            const url = $form.attr("action");
            const $file = $form.find("input[name='file']");
            const body = new FormData();
            body.append("video", $file.prop('files')[0]);
            $.ajax({
                url: url,
                type: 'post',
                data: body,
                contentType: false,
                processData: false,
            }).done((src) => {
                $('#upload-btn').remove();
                $("#video-area").html(
                    $('<video>').prop({
                        src: src,
                        class: 'img-fluid',
                        controls: true,
                        style: "max-width:50vw; max-height:40vh;"
                    })
                );
                $('#select_scene').show();
                $('#select_scene').prop("disabled", true);
            });
        });

        $('#select-btn').click(() => {
            $('#select-btn').remove();
            start_loading();
            const video = document.querySelector('video');
            const fileNameIndex = video.src.lastIndexOf("/") + 1;
            const filename = video.src.substr(fileNameIndex);
            $.post('/select_scene', {
                video_name: filename,
                video_currentTime: video.currentTime,
            }, function (url) {
                location.href = url
            });
        });
    });

    function start_loading() {
        const h = $(window).height();
        $('#wrap').css('display', 'none');
        $('#loader-bg ,#loader').height(h).css('display', 'block');
    }

</script>
{% endblock %}